export const dark_mode = {
    name: 'darkMode',
    anchor: '#1034a6',
    anchorVisited: '#440381',
    borderDark: '#49014B',
    borderDarkest: '#49014B',
    borderLight: '#E635EC',
    borderLightest: '#E635EC', // focus nav background
    canvas: '#ffffff',
    canvasText: '#fff',
    canvasTextDisabled: '#05427f',
    canvasTextDisabledShadow: '#7ebfff',
    canvasTextInvert: '#000000',
    checkmark: '#000000',
    checkmarkDisabled: '#05427f',
    flatDark: '#9e9e9e',
    flatLight: '#1F0220', // time stamp button color
    focusSecondary: '#E635EC',
    headerBackground: '#E635EC',
    headerNotActiveBackground: 'E635EC',
    headerNotActiveText: '#7f7f7f',
    headerText: '#ffffff',
    hoverBackground: '#E635EC', // hover
    material: '#1F0220', // nav and navbar color
    materialDark: '#9a9e9c',
    materialText: '#ffffff', // text color
    materialTextDisabled: '#05427f',
    materialTextDisabledShadow: '#c6c6c6',
    materialTextInvert: '#000000',
    progress: '#F46036',
    tooltip: '#E635EC',
}

export const light_mode = {
    name: 'lightMode',
    anchor: '#1034a6',
    anchorVisited: '#440381',
    borderDark: '#848584',
    borderDarkest: '#0a0a0a',
    borderLight: '#dfdfdf',
    borderLightest: '#fefefe',
    canvas: '#ffffff',
    canvasText: '#0a0a0a',
    canvasTextDisabled: '#848584',
    canvasTextDisabledShadow: '#fefefe',
    canvasTextInvert: '#fefefe',
    checkmark: '#0a0a0a',
    checkmarkDisabled: '#848584',
    flatDark: '#9e9e9e',
    flatLight: '#d8d8d8',
    focusSecondary: '#fefe03',
    headerBackground: '#060084',
    headerNotActiveBackground: '#7f787f',
    headerNotActiveText: '#c6c6c6',
    headerText: '#fefefe',
    hoverBackground: '#060084',
    material: '#c6c6c6',
    materialDark: '#9a9e9c',
    materialText: '#0a0a0a',
    materialTextDisabled: '#848584',
    materialTextDisabledShadow: '#fefefe',
    materialTextInvert: '#fefefe',
    progress: '#060084',
    tooltip: '#fefbcc',
}
